In [1]:
from datetime import date
import hisepy
import os
import pandas as pd
import polars as pl
import re

In [2]:
if not os.path.isdir('output'):
    os.mkdir('output')

In [3]:
def element_id(n = 3):
    import periodictable
    from random import randrange
    rand_el = []
    for i in range(n):
        el = randrange(0,118)
        rand_el.append(periodictable.elements[el].name)
    rand_str = '-'.join(rand_el)
    return rand_str

### Sample Metadata

In [4]:
meta_uuid = '046c1c7f-e820-47bb-b407-62469057a5b4'

In [5]:
meta_file = hisepy.cache_files([meta_uuid])[0]

In [6]:
meta = pl.read_csv(meta_file)

In [7]:
meta.shape

(108, 67)

In [8]:
meta.head()

shape: (5, 67)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│     ┆ cohort.coh ┆ subject.su ┆ subject.bi ┆ … ┆ White      ┆ Lactate    ┆ Magnesium ┆ Phosphate │
│ --- ┆ ortGuid    ┆ bjectGuid  ┆ ologicalSe ┆   ┆ Blood Cell ┆ Dehydrogen ┆ ---       ┆ ---       │
│ i64 ┆ ---        ┆ ---        ┆ x          ┆   ┆ Count      ┆ ase        ┆ str       ┆ str       │
│     ┆ str        ┆ str        ┆ ---        ┆   ┆ (WBC)      ┆ ---        ┆           ┆           │
│     ┆            ┆            ┆ str        ┆   ┆ ---        ┆ str        ┆           ┆           │
│     ┆            ┆            ┆            ┆   ┆ f64        ┆            ┆           ┆           │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0   ┆ BR1        ┆ BR1001     ┆ Female     ┆ … ┆ 4.3        ┆ null       ┆ null      ┆ null      │
│ 1   ┆ BR1        ┆ BR1002     ┆ Male       ┆ … ┆ 5.5        ┆ null       ┆ null      ┆ null      │
│ 2   ┆ BR1        ┆ BR1003     ┆ Female     ┆ … ┆ 4.1        ┆ null       ┆ null      ┆ null      │
│ 3   ┆ BR1        ┆ BR1004     ┆ Male       ┆ … ┆ 2.9        ┆ null       ┆ null      ┆ null      │
│ 4   ┆ BR1        ┆ BR1005     ┆ Female     ┆ … ┆ 7.4        ┆ null       ┆ null      ┆ null      │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [9]:
age_groups = {
    'BR1': 'Young Adult',
    'BR2': 'Older Adult',
    'UP1': 'Children'
}

In [10]:
meta = meta.with_columns(
    pl.Series(
        name = 'subject.ageGroup',
        values = [age_groups[c] for c in meta['cohort.cohortGuid']]
    )
)

In [11]:
keep_meta_cols = [
    'cohort.cohortGuid',
    'subject.subjectGuid',
    'sample.sampleKitGuid',
    'subject.biologicalSex',
    'subject.birthYear',
    'subject.ageGroup',
    'subject.race',
    'subject.ethnicity',
    'subject.cmv',
    'sample.visitName',
    'sample.subjectAgeYears',
]

In [12]:
meta = meta.select(keep_meta_cols)

In [13]:
meta.head()

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cohort.co ┆ subject.s ┆ sample.sa ┆ subject.b ┆ … ┆ subject.e ┆ subject.c ┆ sample.vi ┆ sample.s │
│ hortGuid  ┆ ubjectGui ┆ mpleKitGu ┆ iological ┆   ┆ thnicity  ┆ mv        ┆ sitName   ┆ ubjectAg │
│ ---       ┆ d         ┆ id        ┆ Sex       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ eYears   │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ BR1       ┆ BR1001    ┆ KT00001   ┆ Female    ┆ … ┆ Non-Hispa ┆ Negative  ┆ Flu Year  ┆ 32       │
│           ┆           ┆           ┆           ┆   ┆ nic       ┆           ┆ 1 Day 0   ┆          │
│           ┆           ┆           ┆           ┆   ┆ origin    ┆           ┆           ┆          │
│ BR1       ┆ BR1002    ┆ KT00002   ┆ Male      ┆ … ┆ Non-Hispa ┆ Negative  ┆ Flu Year  ┆ 28       │
│           ┆           ┆           ┆           ┆   ┆ nic       ┆           ┆ 1 Day 0   ┆          │
│           ┆           ┆           ┆           ┆   ┆ origin    ┆           ┆           ┆          │
│ BR1       ┆ BR1003    ┆ KT00003   ┆ Female    ┆ … ┆ Non-Hispa ┆ Negative  ┆ Flu Year  ┆ 30       │
│           ┆           ┆           ┆           ┆   ┆ nic       ┆           ┆ 1 Day 0   ┆          │
│           ┆           ┆           ┆           ┆   ┆ origin    ┆           ┆           ┆          │
│ BR1       ┆ BR1004    ┆ KT00004   ┆ Male      ┆ … ┆ Non-Hispa ┆ Negative  ┆ Flu Year  ┆ 30       │
│           ┆           ┆           ┆           ┆   ┆ nic       ┆           ┆ 1 Day 0   ┆          │
│           ┆           ┆           ┆           ┆   ┆ origin    ┆           ┆           ┆          │
│ BR1       ┆ BR1005    ┆ KT00006   ┆ Female    ┆ … ┆ Non-Hispa ┆ Negative  ┆ Flu Year  ┆ 27       │
│           ┆           ┆           ┆           ┆   ┆ nic       ┆           ┆ 1 Day 0   ┆          │
│           ┆           ┆           ┆           ┆   ┆ origin    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
data_uuids = [
    '7c2d668a-b851-4087-ba31-408de4ce889c',
    '00753770-4803-4947-a290-e7469c410067',
    '1a528317-bbf3-45b7-82c9-529577cf0b15',
    '55d5d20a-506a-459e-8315-7d66276fb8f9',
    '59f5f656-085f-4d0b-a240-68a9eb15e68e',
    'b494cce8-1314-4f6e-9666-42f0c6e1c702',
    'a2e01b9b-2ed9-4b3a-a43a-48a4bc2af007'
]

In [15]:
data_files = []
for uuid in data_uuids:
    data_files.append(hisepy.cache_files([uuid])[0])

In [16]:
data_list = []
for file in data_files:
    df = pd.read_csv(file)
    data_list.append(pl.DataFrame(df))

/tmp/ipykernel_1056/3137820088.py:3: DtypeWarning: Columns (53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_1056/3137820088.py:3: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_1056/3137820088.py:3: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_1056/3137820088.py:3: DtypeWarning: Columns (27,28,29,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_1056/3137820088.py:3: DtypeWarning: Columns (34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

### Update the first dataset
This is the bridging reference sample, so it's missing columns related to bridging

In [17]:
data_list[0] = data_list[0].with_columns(
    pl.col('LOD').alias('LOD_bridged'),
    pl.col('NPX').alias('NPX_bridged'),
    pl.lit(0).cast(pl.Float64).alias('BatchOffset')
)

In [18]:
rename_cols = {
    'NPX': 'olink.NPX_raw',
    'NPX_qry': 'olink.NPX_raw',
    'NPX_bridged': 'olink.NPX_norm',
    'PlateID': 'olink.plate_id',
    'PlateID_qry': 'olink.plate_id',
    'LOD': 'olink.LOD_raw',
    'LOD_qry': 'olink.LOD_raw',
    'LOD_bridged': 'olink.LOD_norm',
    'Assay': 'olink.assay',
    'SampleID': 'specimen.specimenGuid',
    'OlinkID': 'olink.assay_id',
    'Panel': 'olink.panel',
    'UniProt': 'olink.uniprot_id',
    'BatchOffset': 'olink.norm_offset'
}

In [19]:
renamed_data = []
for data in data_list:
    for old, new in rename_cols.items():
        if old in data.columns:
            data = data.rename({old: new})
    renamed_data.append(data)

In [20]:
select_cols = list(set(rename_cols.values()))

In [21]:
select_cols

['specimen.specimenGuid',
 'olink.NPX_raw',
 'olink.LOD_raw',
 'olink.panel',
 'olink.plate_id',
 'olink.LOD_norm',
 'olink.assay',
 'olink.uniprot_id',
 'olink.NPX_norm',
 'olink.norm_offset',
 'olink.assay_id']

In [22]:
selected_list = []
for data in renamed_data:
    data = data[select_cols]
    selected_list.append(data)
all_data = pl.concat(selected_list)

In [23]:
specimens = all_data['specimen.specimenGuid'].unique().to_list()
kits = [re.sub('PL([0-9]+)-.+','KT\\1',specimen) for specimen in specimens]
specimen_to_kit = dict(zip(specimens, kits))

In [24]:
all_data = all_data.with_columns(
    pl.Series(
        name = "sample.sampleKitGuid", 
        values = [specimen_to_kit[s] for s in all_data['specimen.specimenGuid']]
    ),
    pl.col('olink.plate_id').str.replace('_.+', '').alias('olink.batch_id')
)

In [25]:
all_data.shape

(3743263, 13)

In [26]:
all_data.head()

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ specimen. ┆ olink.NPX ┆ olink.LOD ┆ olink.pan ┆ … ┆ olink.nor ┆ olink.ass ┆ sample.sa ┆ olink.ba │
│ specimenG ┆ _raw      ┆ _raw      ┆ el        ┆   ┆ m_offset  ┆ ay_id     ┆ mpleKitGu ┆ tch_id   │
│ uid       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ id        ┆ ---      │
│ ---       ┆ f64       ┆ f64       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ str      │
│ str       ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ PL00205-0 ┆ 0.3975    ┆ -6.3078   ┆ Neurology ┆ … ┆ 0.0       ┆ OID21145  ┆ KT00205   ┆ 20201752 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PL00205-0 ┆ 0.164     ┆ -5.2385   ┆ Neurology ┆ … ┆ 0.0       ┆ OID21153  ┆ KT00205   ┆ 20201752 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PL00205-0 ┆ 0.8896    ┆ -5.0161   ┆ Neurology ┆ … ┆ 0.0       ┆ OID21136  ┆ KT00205   ┆ 20201752 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PL00205-0 ┆ null      ┆ null      ┆ Neurology ┆ … ┆ 0.0       ┆ OID21119  ┆ KT00205   ┆ 20201752 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PL00205-0 ┆ 1.0911    ┆ 1.1751    ┆ Neurology ┆ … ┆ 0.0       ┆ OID20867  ┆ KT00205   ┆ 20201752 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [27]:
all_data['olink.batch_id'].unique().sort()

shape: (7,)
Series: 'olink.batch_id' [str]
[
	"20201752"
	"20211036"
	"20211037"
	"20212223"
	"Q-02017"
	"Q-04064"
	"Q-09225"
]

In [28]:
test = all_data['specimen.specimenGuid'].str.contains('02284')

In [29]:
sum(test)

2944

In [30]:
order_cols = [
    'sample.sampleKitGuid',
    'specimen.specimenGuid',
    'olink.batch_id',
    'olink.plate_id',
    'olink.panel',
    'olink.assay',
    'olink.assay_id',
    'olink.uniprot_id',
    'olink.norm_offset',
    'olink.NPX_raw',
    'olink.NPX_norm',
    'olink.LOD_raw',
    'olink.LOD_norm'
]

In [31]:
atlas_data = all_data.select(order_cols).filter(
    pl.col('sample.sampleKitGuid').is_in(meta['sample.sampleKitGuid'])
)

In [32]:
atlas_data.shape

(158931, 13)

In [33]:
len(atlas_data['sample.sampleKitGuid'].unique())

108

In [34]:
len(atlas_data['specimen.specimenGuid'].unique())

108

In [35]:
len(set(meta['sample.sampleKitGuid']).intersection(set(atlas_data['sample.sampleKitGuid'])))

108

In [36]:
missing_data = meta.filter(
    ~pl.col('sample.sampleKitGuid').is_in(atlas_data['sample.sampleKitGuid'])
)

In [37]:
missing_data

shape: (0, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cohort.co ┆ subject.s ┆ sample.sa ┆ subject.b ┆ … ┆ subject.e ┆ subject.c ┆ sample.vi ┆ sample.s │
│ hortGuid  ┆ ubjectGui ┆ mpleKitGu ┆ iological ┆   ┆ thnicity  ┆ mv        ┆ sitName   ┆ ubjectAg │
│ ---       ┆ d         ┆ id        ┆ Sex       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ eYears   │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [38]:
atlas_data = atlas_data.join(
    meta,
    how = 'left',
    on = 'sample.sampleKitGuid'
)

In [39]:
out_file = 'output/aifi_hiha_all_olink_{d}.csv'.format(d = date.today())

In [40]:
atlas_data.write_csv(out_file)

## Upload data to HISE

Finally, we'll use `hisepy.upload.upload_files()` to send a copy of our output to HISE to use for downstream analysis steps.

In [41]:
study_space_uuid = '64097865-486d-43b3-8f94-74994e0a72e0'
title = 'HIHA Olink Data for File Sets {d}'.format(d = date.today())

In [42]:
search_id = element_id()
search_id

'aluminum-magnesium-argon'

In [43]:
in_files = [meta_uuid] + data_uuids
in_files

['046c1c7f-e820-47bb-b407-62469057a5b4',
 '7c2d668a-b851-4087-ba31-408de4ce889c',
 '00753770-4803-4947-a290-e7469c410067',
 '1a528317-bbf3-45b7-82c9-529577cf0b15',
 '55d5d20a-506a-459e-8315-7d66276fb8f9',
 '59f5f656-085f-4d0b-a240-68a9eb15e68e',
 'b494cce8-1314-4f6e-9666-42f0c6e1c702',
 'a2e01b9b-2ed9-4b3a-a43a-48a4bc2af007']

In [44]:
out_files = [out_file]
out_files

['output/aifi_hiha_all_olink_2025-04-25.csv']

In [45]:
hisepy.upload.upload_files(
    files = out_files,
    study_space_id = study_space_uuid,
    title = title,
    input_file_ids = in_files,
    destination = search_id
)

checking if conda environment can compile...

{'Message': 'General Okay-ness',
 'VisualizationId': '00000000-0000-0000-0000-000000000000',
 'AbstractionId': '00000000-0000-0000-0000-000000000000',
 'TraceId': '96a42993-6ec1-4138-afab-c0a54549c1b5',
 'ProcessId': '3115391a-4d58-4ea8-8e6c-8d83538e1669',
 'WorkflowId': 'f0d04bfd-467e-49e9-a3bb-b72dcf0278bd',
 'FileIds': ['fb897788-03e7-4f4c-abfd-a1af2e335015']}

In [46]:
import session_info
session_info.show()